"""empty message

Revision ID: 5262571ce7eb
Revises: 
Create Date: 2024-09-18 10:02:14.072381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5262571ce7eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    # ### end Alembic commands ###
